spring.datasource.url=jdbc:postgresql://localhost:5432/userdb
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://127.0.0.1:9000
