spring.application.name=authservice
server.port=9000

spring.profiles.active=dev

auth.clients.gateway-client.secret=${AUTH_SERVICE_GATEWAY_CLIENT_SECRET}
auth.clients.service-client.secret=${AUTH_SERVICE_CLIENT_SECRET}

userservice.internal.base-url=${USERSERVICE_BASE_URL}