spring.application.name=authservice
server.port=9000

auth.clients.gateway-client.secret=${AUTH_SERVICE_GATEWAY_CLIENT_SECRET:secret}
auth.clients.service-client.secret=${AUTH_SERVICE_CLIENT_SECRET:service-secret}

userservice.internal.base-url=http://localhost:8081