spring.application.name=bff
server.port=8080

spring.security.oauth2.client.provider.authservice.issuer-uri=http://127.0.0.1:9000
spring.security.oauth2.client.registration.authservice.client-id=gateway-client
spring.security.oauth2.client.registration.authservice.client-secret=secret
spring.security.oauth2.client.registration.authservice.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.authservice.redirect-uri=http://localhost:8081/login/oauth2/code/authservice
spring.security.oauth2.client.registration.authservice.scope=user.read,openid