spring.application.name=bff
server.port=8080

services.user-service.base-url=${USER_SERVICE_URL:http://localhost:8081}
services.message-service.base-url=${MESSAGE_SERVICE_URL:http://localhost:8082}

spring.security.oauth2.client.provider.authservice.issuer-uri=${AUTH_SERVICE_ISSUER_URI:http://127.0.0.1:9000}
spring.security.oauth2.client.registration.authservice.client-id=${BFF_CLIENT_ID:gateway-client}
spring.security.oauth2.client.registration.authservice.client-secret=${BFF_CLIENT_SECRET:secret}
spring.security.oauth2.client.registration.authservice.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.authservice.redirect-uri=${BFF_REDIRECT_URI:http://localhost:8080/login/oauth2/code/authservice}
spring.security.oauth2.client.registration.authservice.scope=user.read,openid